services:
  - type: web
    name: habit-tracker
    runtime: node
    repo: https://github.com/naitikmi/Habit-Tracker
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_connection_string
      - key: ADMIN_PASSWORD
        value: your_admin_password
      - key: JWT_SECRET
        value: your_jwt_secret
