services:
  - type: web
    name: habit-tracker
    runtime: node
    repo: https://github.com/naitikmi/Habit-Tracker
    plan: free
    buildCommand: npm install
    startCommand: node server.js

databases:
  - name: habit-tracker-db
    plan: free
    databaseType: postgres
    ipAllowList: []
